name: Feature request
description: Propose an enhancement
title: "feat: "
labels:
  - enhancement
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion!

        Please keep scope focused. If this relates to the Freebusy API contract, include any relevant details.

  - type: textarea
    id: problem
    attributes:
      label: Problem statement
      description: What problem are you trying to solve?
      placeholder: "As a user, I want ... so that ..."
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to see built?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you considered?
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Mockups, screenshots, links, API payload examples, etc.
    validations:
      required: false
